#!/usr/bin/perl -w
#ensure arguments are correctly used
die "Usage: ./courses.pl <COURSENAME>, optional flags: t or f.\n" if ($#ARGV+1 < 1);

for(@ARGV){
	if($_ =~ /-t$/){
		$tf =1;
	}
	elsif($_ =~ /-d$/){
		$df =1;
	}
	elsif($_ =~ /[A-Z]{4}[0-9]{4}/){
		push @course, $_;
	} 
}


for $c (@course) {
	$url =  "http://www.timetable.unsw.edu.au/current/$c.html";
	open $P, "wget -q -O- $url|" or die $!;
	&dtable($url,$c,$P) if(!($tf || $df));
	close $P;
}
#..------------------------------------------------------------------------------

#semester ccode wday timeinhr\nsamething
sub dtable{#checked
	(my $link, my $course, my $Page) = @_;
	while($line = <$Page>){
		 #irrelevant details 
		last if($line =~ /CLASSES - Detail/);
		if ($line =~ /<td class="data"><a href="#([SX][12])-[0-9]{4}">Lecture<\/a><\/td>/){
			$sem = $1;
			 #$skip 5 lines and read the following line
			$line = <$Page> for(1..6) ;
			 #<td class="data">Mon 14:00 - 16:00 (Weeks:1-9,10-12), Wed 17:00 - 18:00 (Weeks:1-9,10-12)</td>
			$line =~ s/ *<td class="data">//;
			$line =~ s/<\/td>//;
			if (!($line)){
				next;
			} 
			#print $line."\n";
			$line =~ s/ \(Weeks:[^)]*\)//g;
			$line =~ s/:00//g;
			$line =~ s/- //g;
			chomp $line;
			#Mon 14 16, Wed 17 18
			#print $line."-----------------------------\n";
			@data = split(", ",$line); 
			
			#Mon 14 16
			my @lazy;
			for (@data){
				if($_ =~ /^[A-Z][a-z]{2}$/){#to handle "wed,fri 09 - 11"
					push @lazy, $_;
					next;
				}
				
				($day,$start,$end) = split(" ", $_);
				$hr = scalar $start;
				if(@lazy){
					for (@lazy){
						while ($hr < scalar $end){
							print("$_ $course $day $hr\n");
							$hr++;
						}
						$hr = scalar $start; 
					}
				@lazy = ();
				}
				while ($hr < scalar $end){
					print("$sem $course $day $hr\n");
					$hr++;
				} 
			}
		}	
	}
}
